# Generated by Django 5.1.3 on 2024-12-06 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieCd', models.IntegerField(help_text='영화 ID', primary_key=True, serialize=False)),
                ('movieNm', models.CharField(help_text='영화명(국문)', max_length=255)),
                ('tmdb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='accounts.tmdbmovie')),
            ],
        ),
    ]
