# Generated by Django 5.1.3 on 2024-11-29 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_favorite_movie_id'),
        ('kobis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='kobis.movie'),
        ),
    ]
