# Generated by Django 5.1.3 on 2024-12-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_expert_review',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
