# Generated by Django 5.1.3 on 2024-12-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_review_is_expert_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_expert_review',
            field=models.BooleanField(default=False),
        ),
    ]
