# Generated by Django 5.1.3 on 2024-11-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_favorite_movie_id'),
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preference',
        ),
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.ManyToManyField(blank=True, related_name='preferred_by', to='tmdb.genre'),
        ),
    ]
