# Generated by Django 5.1.3 on 2024-12-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_tmdbmovie_remove_review_is_expert_review_and_more'),
        ('tmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preference',
        ),
        migrations.AddField(
            model_name='user',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='users', to='tmdb.genre'),
        ),
    ]
