# Generated by Django 5.1.3 on 2024-12-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='사용자 프로필 이미지', null=True, upload_to='profile_images/'),
        ),
    ]
