# Generated by Django 5.1.3 on 2024-12-04 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_preference_user_genres'),
        ('kobis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='movie_id',
            new_name='movieCd',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'movieCd')},
        ),
    ]
