# Generated by Django 5.1.3 on 2024-11-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_review_is_expert_review_user_groups_user_is_expert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=10.0),
        ),
    ]
