# Generated by Django 5.1.3 on 2024-12-04 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', help_text='채팅박스 제목', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='채팅박스 생성 시간')),
                ('user', models.ForeignKey(help_text='이 채팅박스를 소유한 사용자', on_delete=django.db.models.deletion.CASCADE, related_name='chat_boxes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='사용자 또는 AI가 보낸 메시지 내용')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='메시지가 작성된 시간')),
                ('is_from_user', models.BooleanField(default=True, help_text='True면 사용자가 보낸 메시지, False면 AI가 보낸 메시지')),
                ('chatbox', models.ForeignKey(help_text='이 채팅 로그가 속한 채팅박스', on_delete=django.db.models.deletion.CASCADE, related_name='chat_logs', to='ai.chatbox')),
            ],
        ),
    ]
